#!/bin/bash
# Copyright (c) 2019 PirateChain - no rights reserved

# set working directory to the location of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

NAME=PIRATE

CLI=${KOMODOCLI:-./komodo-cli}
$CLI -ac_name=$NAME "$@"
