# we are using separate workflow because CI producing test binaries with CPPFLAGS=-DTESTMODE

name: Pirate build - Aarch64 cross compile 20.04


on:
  push:
    branches:
    - master
    - beta



jobs:

  linux-build:
    name: Linux Build
    # using there as old release as possible with GHA worker to provide better compatibility
    runs-on: ubuntu-20.04
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - name: Shortify commit sha
        shell: bash
        run: echo "sha_short=$(echo ${GITHUB_SHA::7})" >> "$GITHUB_OUTPUT"
        id: shortify_commit

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Cargo Cross Compile (Linux)
        run: |
          echo '[target.aarch64-unknown-linux-gnu]' > /home/runner/.cargo/config
          echo 'ar = "/usr/bin/aarch64-linux-gnu-ar-9"' >> /home/runner/.cargo/config
          echo 'linker = "/usr/bin/aarch64-linux-gnu-gcc-9"' >> /home/runner/.cargo/config

      - name: Install deps (Linux)
        run: |
          sudo apt-get update  # prevents repo404 errors on apt-remove below
          sudo apt-get upgrade -y
          sudo apt-get install -y build-essential pkg-config m4 g++-multilib autoconf libtool libncurses-dev unzip git python3 python3-zmq zlib1g-dev wget libcurl4-gnutls-dev bsdmainutils curl libsodium-dev bison
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          ./zcutil/build-qt-arm.sh -j$(nproc)
          aarch64-linux-gnu-strip src/pirated
          aarch64-linux-gnu-strip src/pirate-cli
          aarch64-linux-gnu-strip pirate-qt-arm
          zip --junk-paths pirate-aarch64 src/pirated src/pirate-cli
          zip --junk-paths pirate-qt-aarch64 pirate-qt-arm
      - name: Upload pirate-aarch64.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: pirate-linux-aarch64
          path: ./pirate-aarch64.zip
      - name: Upload pirate-qt-aarch64.zip as artifact
        uses: actions/upload-artifact@v1
        with:
          name: pirate-qt-aarch64
          path: ./pirate-qt-aarch64.zip
